version: '3.8'

services:

  funbro-data-collector:
    build:
      dockerfile: docker/Dockerfile
      context: .
    container_name: funbro-data-collector
    environment:
      - ENVIRONMENT=production # either development or production
    env_file:
      - .env
    volumes:
    - .credentials:/app/.credentials:ro
    depends_on:
      - "db"
    networks:
      funbro-data-collector-network:
        ipv4_address: 172.28.1.1

  db:
    container_name: postgres-db
    image: postgres:13
    cap_add:
      - SYS_NICE
    environment:
      - POSTGRES_DATABASE=funbro
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test
      - POSTGRES_MULTIPLE_DATABASES=funbro
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d:ro
    networks:
      funbro-data-collector-network:
        ipv4_address: 172.28.1.2

networks:
  funbro-data-collector-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
