version: '3.3'

services:

  funbro-data-collector:
    build:
      dockerfile: docker/Dockerfile
      context: .
    container_name: funbro-data-collector
    environment:
      - POSTGRES_DATABASE_HOST_FIELD=172.28.1.2 # see db service below, this is a local network
      - POSTGRES_DATABASE_PORT_FIELD=5432
      - POSTGRES_DATABASE_USER_FIELD=test_user
      - POSTGRES_DATABASE_PASSWORD_FIELD=test
    # entrypoint: ["./wait-for-db.sh", "db", "--"]
    volumes:
      - .:/app
    depends_on:
      - "db"
    networks:
      funbro-data-collector-network:
        ipv4_address: 172.28.1.1

  db:
    container_name: postgres-db
    image: postgres:11
    cap_add:
      - SYS_NICE
    environment:
      - POSTGRES_DATABASE=databases
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test
      - POSTGRES_MULTIPLE_DATABASES=funbro
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d:rw
    networks:
      funbro-data-collector-network:
        ipv4_address: 172.28.1.2

networks:
  funbro-data-collector-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
