version: '3.8'

services:

  funbro-data-collector:
    build:
      dockerfile: docker/Dockerfile
      context: .
    container_name: funbro-data-collector
    env_file:
      - .env.dev
    volumes:
    - .:/app
    depends_on:
      - "db"

  db:
    container_name: postgres-db
    image: postgres:13
    cap_add:
      - SYS_NICE
    environment:
      - POSTGRES_DATABASE=funbro
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test
      - POSTGRES_MULTIPLE_DATABASES=funbro
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d:ro

volumes:
  postgres-volume: